version: '3.3'

services:
    db:
      image: mysql:5.7
      container_name: srv_mysql
      volumes:
        - db_data:/var/lib/mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_DATABASE: ${MYSQL_DATABASE}

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      container_name: phpmyadmin
      environment:
        - PMA_ARBITRARY=${PMA_ARBITRARY}
        - PMA_HOST=${PMA_HOST}
        - PMA_PORT=${PMA_PORT}
        - PMA_USER=${PMA_USER}
        - PMA_PASSWORD=${PMA_PASSWORD}
      restart: always
      ports:
        - "8081:80"
      volumes:
        - phpmyadmin_session:/sessions

    nextcloud:
      depends_on:
        - db
        # - onlyoffice
      image: nextcloud:latest
      container_name: srv_nextcloud
      ports:
        - "8080:80"
      volumes:
        - nextcloud_data:/var/www/html
      restart: always
      environment:
        MYSQL_HOST: ${NEXTCLOUD_DB_HOST}
        MYSQL_USER: ${NEXTCLOUD_DB_USER}
        MYSQL_PASSWORD: ${NEXTCLOUD_DB_PASSWORD}
        MYSQL_DATABASE: ${NEXTCLOUD_DB_NAME}
        NEXTCLOUD_TABLE_PREFIX: ${NEXTCLOUD_TABLE_PREFIX}
        NEXTCLOUD_ADMIN_USER: ${NEXTCLOUD_ADMIN_USER}
        NEXTCLOUD_ADMIN_PASSWORD: ${NEXTCLOUD_ADMIN_PASSWORD}

    # onlyoffice:
    #   image: onlyoffice/documentserver:latest
    #   container_name: srv_onlyoffice
    #   ports:
    #     - "80:80"
    #   volumes:
    #     - onlyoffice_data:/var/www/onlyoffice/Data
    #   restart: always
    #   environment:
    #     DOCUMENT_SERVER_PORT_80_TCP_ADDR: srv_onlyoffice
       

volumes:
    db_data:
    phpmyadmin_session:
    nextcloud_data:
    # onlyoffice_data: