# ++++++++++++++++++++++++++++++++++++++ 
#  Ubuntu 18.04 Apache PHP7.2
# ++++++++++++++++++++++++++++++++++++++ 


# image de base.
FROM ubuntu:18.04

MAINTAINER Dylan Gouzenne <contact@dylangouzenne.fr>

ENV DEBIAN_FRONTEND=noninteractive

# Installation du serveur web Apache2 avec PHP + vim, curl et git.
RUN apt-get update && apt-get install -y \
    apt-utils \
    vim \
    curl \
    git \
    apache2 \
    libapache2-mod-php7.2 \
    php7.2-intl \
    php7.2-cli \
    php7.2-xml \
    php7.2-tokenizer \
    php7.2-ctype \
    php7.2-bcmath \
    php7.2-json \
    php7.2-pdo \
    php7.2-mysql \
    php7.2-zip \
    php7.2-mbstring && \
    a2enmod rewrite && \
    rm -rf /var/www/html

# Install composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

# ajout du Path laravel dans le fichier .bashrc
COPY config/.bashrc /root/.bashrc

# instalation de laravel
RUN composer create-project -d /var/www --prefer-dist laravel/laravel app

# copie des fichier conf apache et php
COPY config/apache2.conf /etc/apache2/apache2.conf
COPY config/000-default.conf /etc/apache2/sites-available/000-default.conf
COPY config/custom.php.ini /etc/php/7.2/apache2/conf.d/custom.php.ini

# création de l'utilisateur laravel
#RUN adduser --disabled-password --gecos '' laravel

# utiliser l'utilisateur laravel 
#USER laravel

# Répertoire de travail.
WORKDIR /var/www/

# Port exposer.
EXPOSE 80
EXPOSE 8000

# Point d'entrée.
ENTRYPOINT /usr/sbin/apache2ctl -D FOREGROUND